services:
  - type: web
    name: kakeibo-app
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/src/data/prod.db
    disk:
      name: kakeibo-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1